### ISSUE TITLE
README: Broken screenshot.

### ISSUE THREAD

**Issue by shurcooL** [rakyll/gom#22]
https://googledrive.com/host/0ByfSjdPVs9MZbkhjeUhMYzRTeEE/gom-screenshot.png is 404.

![image](https://cloud.githubusercontent.com/assets/1924134/20250061/e7b8c604-a9bc-11e6-8cfe-93da47c955f6.png)

**Comment by rakyll** [comment]
I was about to deprecate this tool, remove the screenshot instead?

**Comment by dmitshur** [comment]
This has been resolved via 183a9e70f4777aa03d377d21a0ed023a6afac141, closing.

**Comment by dgryski** [comment]
Re: deprecation,  did you have a replacement in mind?

**Comment by rakyll** [comment]
@dgryski I am wishing someone from the community can take over or fork. I cannot maintain the tool due to limited bandwidth :(
